[project]
authors = [
  "Shivasankar <shivasankar.ka@gmail.com>",
  "MadAlex1997 <>",
  "Yuhao Zhu (朱宇浩) <dr.yuhao.zhu@outlook.com>",
  "mmenendezg <>",
  "sandstromviktor <>",
  "durnwalder <>",
]
channels = [
  "conda-forge",
  "https://conda.modular.com/max",
  "https://repo.prefix.dev/modular-community",
]
description = "NuMojo is a library for numerical computing written in Mojo 🔥"
license = "Apache-2.0"
name = "NuMojo"
platforms = ["osx-arm64", "linux-64"]
preview = ["pixi-build"]
readme = "README.MD"
version = "0.7.0"

[package]
name = "numojo"
version = "0.7.0"

[package.build]
backend = {name = "pixi-build-mojo", version = "0.*", channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]}

[package.build.config.pkg]
name = "numojo"

[package.host-dependencies]
mojo = ">=25.6.0,<26"

[package.build-dependencies]
mojo = ">=25.6.0,<26"

[package.run-dependencies]
mojo = ">=25.6.0,<26"

[tasks]
# compile the package and copy it to the tests folder
p = "clear && pixi run package"
package = "pixi run mojo package numojo && cp numojo.mojopkg tests/"

# format the package
format = "pixi run mojo format ./"

# test whether tests pass on the built package
t = "clear && pixi run test"
test = "pixi run package && pixi run mojo test tests -I tests/ && rm tests/numojo.mojopkg"

# run individual tests to avoid overheat
test_core = "pixi run package && pixi run mojo test tests/core -I tests/ && rm tests/numojo.mojopkg"
test_creation = "pixi run package && pixi run mojo test tests/routines/test_creation.mojo -I tests/ && rm tests/numojo.mojopkg"
test_functional = "pixi run package && pixi run mojo test tests/routines/test_functional.mojo -I tests/ && rm tests/numojo.mojopkg"
test_indexing = "pixi run package && pixi run mojo test tests/routines/test_indexing.mojo -I tests/ && rm tests/numojo.mojopkg"
test_linalg = "pixi run package && pixi run mojo test tests/routines/test_linalg.mojo -I tests/ && rm tests/numojo.mojopkg"
test_manipulation = "pixi run package && pixi run mojo test tests/routines/test_manipulation.mojo -I tests/ && rm tests/numojo.mojopkg"
test_math = "pixi run package && pixi run mojo test tests/routines/test_math.mojo -I tests/ && rm tests/numojo.mojopkg"
test_random = "pixi run package && pixi run mojo test tests/routines/test_random.mojo -I tests/ && rm tests/numojo.mojopkg"
test_searching = "pixi run package && pixi run mojo test tests/routines/test_searching.mojo -I tests/ && rm tests/numojo.mojopkg"
test_sorting = "pixi run package && pixi run mojo test tests/routines/test_sorting.mojo -I tests/ && rm tests/numojo.mojopkg"
test_statistics = "pixi run package && pixi run mojo test tests/routines/test_statistics.mojo -I tests/ && rm tests/numojo.mojopkg"

# run all final checks before a commit
f = "clear && pixi run final"
final = "pixi run format && pixi run test"

# Automatically Generate doc pages
doc_pages = "mojo doc numojo/ -o docs.json"

# run everything and generate docs before release
release = "clear && pixi run final && pixi run doc_pages"

[dependencies]
mojo = ">=0.25.6,<0.26"
numpy = ">=2.3.2,<3"
python = ">=3.13.5,<3.14"
scipy = ">=1.16.0,<2"
